### ISSUE TITLE
OpenXRay

### ISSUE THREAD

**Issue by ShokerStlk** [Im-dex/xray-162#10]
Привет! Это не совсем проблема, просто хотел сообщить что в гите уже довольно давно есть старый форк движка с обновлённым и рабочим luabind-ом (без буста)  - https://github.com/OpenXRay/xray-16 (/dev-ветка)
На тот случаи если вы про это не знали. 

Если есть возможность - дальнейшую работу над движком лучше проводить в одном месте, чтобы не распылять свои силы.
Если же отдельный репозитории был создан сознательно - тогда можно игнорировать\удалить это сообщение.

**Comment by Im-dex** [comment]
@ShokerStlk Привет. Спасибо за сообщение, но как Вы сами писали в одном из issues: openxray - "seriously broken". И, думаю, в текущем состоянии мало кто захочет с ним иметь дело.

**Comment by ShokerStlk** [comment]
Мы его почти починили (надеюсь). По крайнем мере почти всё что я там перечислил уже исправлено.  (висит в pull request точнее :D, часть ещё чуть позже добавлю), может конечно в процессе что то ещё вылезет. Ну вообщем я не настаиваю, желаю успехов.

**Comment by revolucas** [comment]
I've used and modded on Open Xray for 2 years now. I'm not happy with the direction or the changes they've made and decided to use this repo. Nitrocaster renamed classes, files, changed class inheritance, etc. All these things were unnecessary and made it extremely difficult to port useful code from other Xray repos or to keep a fork up to date. Im-dex appears to be doing what needs to be done and only what needs to be done to improve the engine, not OCD behavior by restructuring entire engine.

**Comment by Xottab-DUTY** [comment]
Can we merge your changes to OpenXRay? =)

**Comment by Im-dex** [comment]
@Xottab-DUTY Sure, according to the license :)
