### ISSUE TITLE
Does 64-bit work currently?

### ISSUE THREAD

**Issue by ghost** [Im-dex/xray-162#18]
Sorry for my stupid question, but I can't tell.
For me I get to right when the game is about to load then get an error stating "Too many posts to a semaphore", so mine doesn't appear to be OpenAL related.

**Comment by Im-dex** [comment]
@Swartz27 No, 64-bit build still broken yet. Do you get "Too many posts to a semaphore" error when the game is starting from scratch or when a level is loading from the game menu?

**Comment by ghost** [comment]
@Im-dex I get the error on the 64bit-fix branch right as the game is done loading the level and would normally load.

**Comment by Im-dex** [comment]
@Swartz27 It's ok, level loading isn't fixed yet.
