### ISSUE TITLE
Truncated stacktrace

### ISSUE THREAD

**Issue by Im-dex** [Im-dex/xray-162#20]
Stacktrace is truncated due to illegal registers values assignment to the context.

**Comment by Im-dex** [comment]
New stack trace collector works well.

**Comment by Xottab-DUTY** [comment]
А какие есть кроссплатформенные аналоги bugtrap или что-то подобное?)

**Comment by ForserX** [comment]
@Xottab-DUTY, я вообще не понимаю прок от него сейчас. xrDebug + отладчик MVS за глаза.

**Comment by Im-dex** [comment]
@Xottab-DUTY [breakpad](https://github.com/google/breakpad)

@ForserX Подобные вещи нужны, чтобы не парить пользователей отправкой логов и корок

**Comment by ForserX** [comment]
@Im-dex, окей, я даже в первых попытках BT под свои данные для отправки настраивал. Давай зайдём с другой стороны. Смотри, значит, есть модификация, которая юзает твои сорцы. За их кривые манипуляции с ресурсами к тебе на ящик будет поступать овер-100 мессагов. 

Но, можно вывести, конечно же, поддержку переопределения данных в ресурсы, тогда всё это будет поступать к разработчику, но не факт, что он будет этим заниматься. 

Принудительно? Левые данные, чтоб не забивалось всё. А если ещё и Васян попадёт, то это GG.

**Comment by Im-dex** [comment]
@ForserX Для любительских модов это скорее и не нужно, но если ты хочешь обеспечить хоть какой-то саппорт пользователей, то это реально удобнее, чем на форуме выпрашивать логи или корку. Если репортов поступает много, то их обработку можно автоматизировать, это еще и челлендж неплохой :)

**Comment by Xottab-DUTY** [comment]
@Im-dex слушай, а можешь поподробнее рассказать про blackbox и почему он использовался вместе с bugtrap, если, как я понял, можно было обойтись bugtrap'ом?

**Comment by ForserX** [comment]
@Xottab-DUTY, утилита от майков для деббага. Могу лишь сказать, что она шла ещё от xrDebug.cpp, использовалась для записи в лог. BT не изучал, признаюсь честно, как более-менее в линковке разобрался - выкинул его вон. (О да, те времена, когда я ковырял ТЧ и кричал, что 1.0007 тащит). 

Скорее всего я не прав, пусть меня Антон    ̷п̷о̷б̷ь̷ё̷т̷/поправит

**Comment by Xottab-DUTY** [comment]
От себя добавлю, что в OpenXRay выпилен не BT, а наоборот, BlackBox и используется только один Bugtrap.

P.S. тут-то у меня и всплыл вопрос о кроссплатформенной библиотеке, ведь OpenXRay имеет задел на Linux, а BugTrap виндовый)

**Comment by ForserX** [comment]
@Xottab-DUTY, на теме BT я в прошло году(вроде бы) пересёкся на форуме с вашим OXR организатором. Процитирю, правда дословно уже не помню:"Вот вечно вы BT выпиливаете, я вообще не уверен в том, что тот огрызок (xrDebug) вообще работает". КТТ, но, таки с небольшим апдейтом он работает.

**Comment by Xottab-DUTY** [comment]
Надо пробовать впилить/прикрутить breakpad, если у него есть все возможности, которые есть у BT, BlackBox и DbgHelp (как я понял именно им Антон заменил BT) =)

@ForserX можно даже попробовать его позвать, чтобы он сказал что-нибудь об этом)

О @nitrocaster приди! =)

**Comment by Im-dex** [comment]
Blackbox используется в утилях и редакторах, разрабам gsc видимо было лень перенастраивать bt под них. Главная проблема bt в том, что под x64 он не пашет, и в xray2 его емнип выпилили совсем.

**Comment by ForserX** [comment]
@Im-dex его уже в билде метро2033 выпилили :)

**Comment by Xottab-DUTY** [comment]
@Im-dex хм... А ведь в репо BT указано, что можно под х64 собирать..

**Comment by Im-dex** [comment]
@Xottab-DUTY Собрать то можно, но сходу не заводится. Возможно его настраивать надо как-то по другому, но мне разбираться было лень :) CaptureStackBacktrace вполне себе работает, а публичные сборки гораздо проще по коркам дебажить
