### ISSUE TITLE
Some physics bugs

### ISSUE THREAD

**Issue by ghost** [Im-dex/xray-162#21]
There is a small bug with physics currently. It is most prevalent when you shoot and kill a stalker and they drop their weapon. About a third of the time the weapon will wildly vibrate around, and sometimes go flying through the air. It's actually pretty funny to witness but it's still a bug :P

**Comment by Im-dex** [comment]
@Swartz27 Thanks, for the report. Is this issue present on x64 build only or reproduces on the x86?

**Comment by ghost** [comment]
@Im-dex I have only tested on x64, I don't know if it happens on x86.

**Comment by ForserX** [comment]
Кстати, Декс, давно NanoBot наткнулся на причину багов физики в сталкере. Вроде код, отвечающий за ракеты, емнип. Было обсуждение на АМК форуме, я бы поискал пост, но зарёкся там больше не появляться.

**Comment by Im-dex** [comment]
@ForserX  Главная причина багов физики - это в первую очередь убогий физ движок :) А за подсказку про амк форум спасибо, попробую поискать.

**Comment by ForserX** [comment]
Слушай, а у тебя бага с граф-поинтами не было на оригинальных локациях?

**Comment by Im-dex** [comment]
@ForserX Какого именно? Пока вроде ничего не замечал, но вполне мог и проглядеть.

**Comment by ForserX** [comment]
@Im-dex, у меня просто оригинальные локации на Mixed проверках вылетают.

**Comment by Im-dex** [comment]
Я только релиз собираю, поэтому не замечал

**Comment by ForserX** [comment]
Хм... Ну, моё железо не позволят для тестов в релизе компилить.

**Comment by Im-dex** [comment]
А в чем проблема скомпилить в релизе? Он вроде не особо отличается по прожорливости от дебага

**Comment by ForserX** [comment]
Оптимизация кода занимает час на моём ПК.

**Comment by ForserX** [comment]
@Im-dex 
А как быть с get_signature на релизе? 
https://pp.userapi.com/c837438/v837438782/4b0a4/im3H6RKWF_A.jpg

**Comment by Im-dex** [comment]
@ForserX А что там? И в выделенном куске вообще-то дебаг

**Comment by ForserX** [comment]
@Im-dex в дебаг я уже перевёл, чтоб собиралось. В оригинале он просто отсуствует на релиз-сборке.

**Comment by ghost** [comment]
Just got a crash that I hope helps in some way:

FATAL ERROR
 
[error]Expression    : assertion failed
[error]Function      : CPHActivationShape::Create
[error]File          : X:\xray-162-master\code\engine\xrPhysics\PHActivationShape.cpp
[error]Line          : 177
[error]Description   : _valid( start_pos )

**Comment by Im-dex** [comment]
@Swartz27 Could you please provide a crash dump for this case? It will be more helpful than a stacktrace.

**Comment by ghost** [comment]
@Im-dex Shit, I deleted my logs folder :(  I'll try and get it to happen again, though it was very random.

**Comment by ghost** [comment]
I totally forgot about Nick Galko. He had an x64 repo, it doesn't run properly, but the one thing that did work right was the physics, and in fact he told me this commit has a fix for the physics bugs:

https://bitbucket.org/nick_galko/cop/commits/6295d37

Sorry for not relaying this sooner.

**Comment by Im-dex** [comment]
Nick Galko's collider fix does not work for me. I will try to rewrite this piece of shit at some day.

**Comment by ghost** [comment]
Can confirm this fixes it: https://github.com/ForserX/FRay-Project/commit/059f64eeb3cdecbab6c129067ac41e07a0a93d6e

Tested for more than an hour, physics bug is gone now.

**Comment by ForserX** [comment]
Угу. Мне кажется, что лучше во всех местах поменять dInfinity, т.к. под x64 они вычисляются не правильно.

**Comment by Im-dex** [comment]
@ForserX Само значение dInfinity вычисляется идентично для обеих архитектур. Но видимо из-за игрищ с пресижином и округлениями, которые нельзя полностью повторить для x64, и появляется данная проблема.
