### ISSUE TITLE
Пара вопросов.

### ISSUE THREAD

**Issue by ForserX** [Im-dex/xray-162#24]
1. Проверь создание лога, у меня от твоей FS вместо файла была папка
2. У тебя с дирекшеном смарткаверов на x64 всё в порядке?

**Comment by Im-dex** [comment]
@ForserX Если сюда писать неудобно, можешь на почту писать

>Проверь создание лога, у меня от твоей FS вместо файла была папка

Точно, спасибо! Если файл существует, то все работает - вот и не заметил

>У тебя с дирекшеном смарткаверов на x64 всё в порядке?

Да как-то не замечал каких-либо проблем, в чем именно проявляется?

**Comment by ForserX** [comment]
-> Да как-то не замечал каких-либо проблем, в чем именно проявляется?
https://github.com/ForserX/FRay-Project/issues/9

Сколько дебажим - выловить не можем, откуда идёт. Где-то при подгрузке значений Lua убивает числа, в итоге позиция эверитайм 0.0.0.

**Comment by Im-dex** [comment]
А сейвом, где это происходит можешь поделиться? Или вопроизводится не всегда?

**Comment by ForserX** [comment]
При новой игре, при переходе на уровень, при загрузке сохранения. Иногда, во время игры, становятся нормально, допустим, после того, как кого-то атакуют. Если есть такой баг, посмотри loophole::loophole.

-> Если файл существует, то все работает - вот и не заметил
Мне с этим проще, каждый раз уникальный лог.

-> можешь на почту писать
А это ещё сильнее не переношу, поэтому сюда и пишу.

**Comment by Im-dex** [comment]
У меня никак не воспроизводится, ни при нг, ни при загрузке. Попробуй коммиты пооткатывать, если найдешь где сломалось, то проще понять будет.

**Comment by ForserX** [comment]
@Im-dex, само-забавно, что сидел и проверял до первых коммитов на битбакете. Пару похожих багов профиксил (с дверьми так же было), а причину этого бага так и не нашёл. Ладно, буду дальше мучаться.

**Comment by Im-dex** [comment]
>Мне с этим проще, каждый раз уникальный лог.

Так он и в ваниле уникальный на каждый запуск

>А это ещё сильнее не переношу, поэтому сюда и пишу.

А что переносишь то? :)

Если до первых коммитов проверил, то дело скорее всего не в движке тогда, а в ресурсах. Ничего такого в скриптах не правил?

**Comment by ForserX** [comment]
> А что переносишь то? :)

Различные месседжеры. Весьма удобно. 
> Если до первых коммитов проверил, то дело скорее всего не в движке тогда, а в ресурсах. Ничего такого в скриптах не правил?

Всё, что правил, всё в репозитории. Роли не играет. По приезду домой надо будет сильнейшим образом отдебажить три движка сразу. Win32, x64 и ваниль. Может так и пойму причину. Если бы код джита читабельным был, было бы куда проще.

**Comment by Im-dex** [comment]
>Различные месседжеры. Весьма удобно.

Ну тогда в телеграм если что писать можешь `@Imdex`

Дебажить джит не особо имеет смысл, т.к. там тупо компиляция скриптов в машкод, который потом и исполняется, проще тогда к самим сриптам отладчик подцепить.

**Comment by Im-dex** [comment]
Fixed at 853de7af02d51f5b06e2693ea8544b585c89092e
