### ISSUE TITLE
Update xml parser

### ISSUE THREAD

**Issue by Im-dex** [Im-dex/xray-162#3]
Update tinyxml to version 4.*, or replace with faster xml parsing library.

**Comment by ForserX** [comment]
4.*? Можно ссылку? Максимум 2.6.* нашёл, вкатал, вроде работает.

**Comment by Xottab-DUTY** [comment]
Я так понимаю имелся ввиду TinyXML2, можно найти тут:
https://github.com/leethomason/tinyxml2/releases

Чтобы его поставить, надо побольше работ провести, там же API поменялся =)

**Comment by ForserX** [comment]
Благодарю. Займусь на досуге. Я с сорсфордж брал.

**Comment by ForserX** [comment]
Не особо много работ на стадии компиляции. Единственно немного тупил над альтернативой IterateChild, но потом костыль написал. В одном месте можно просто заменить на FristChildElement(). До тестов не дошёл, ноут сел.

**Comment by ForserX** [comment]
> Чтобы его поставить, надо побольше работ провести, там же API поменялся =) 


Ну... В целом, я запустил двиг. Была проблема с одним конфигом, так и не понял, где именно, где-то в mp текстах, ибо m_Doc.Value() в новом tinyxml2 возвращал 0. 

https://bitbucket.org/sv3nk/fray/commits/c7829dd7c358e3669c182dd4181ae2c1c88bb61f

**Comment by Im-dex** [comment]
@ForserX Ну и как оно? По памяти или скорости загрузки поменялось что-либо?

**Comment by ForserX** [comment]
Даже не смотрел, просто устал от бесплодных попыток профиксить х64, решил отвлечься. Выбор пал на обновление парсера.

**Comment by ForserX** [comment]
Кст, тут по парсеру ещё апдейт. (https://github.com/ForserX/FRay-Project/commit/c3429241a4c1bc38001df0f69bfd099e3537eff7) ((да-да, я переехал на гитхаб с битбакета))

**Comment by Xottab-DUTY** [comment]
@ForserX жалко, что кодировка слетела. Ты репо на bitbucket, надеюсь, не удалил? А то ж не прочесть будет что там было сделано)

**Comment by ForserX** [comment]
Не удалил. 
P.S. В основном кодировка при работе с ветками слетела. 
P.S.S. ну и у первых коммитов. Но там ерунда.

**Comment by Im-dex** [comment]
@ForserX С новосельем :) Спасибо за ссылку, но я выкинул tinyxml и уже почти переехал на pugi

**Comment by ForserX** [comment]
@Im-dex, хм, интересно будет глянуть. Может к себе на макросы потом повешу.

**Comment by Xottab-DUTY** [comment]
Интересно было бы замерить по производительности pugi и tinyxml2. Замерить как они ведут себя именно в сталкере)

**Comment by Im-dex** [comment]
@Xottab-DUTY На глаз разницы не видно, да и в сталкере  не так много xml, чтобы получить какой-то ощутимый профит

**Comment by ForserX** [comment]
@Im-dex, профилировщик MVS юзни.

**Comment by Xottab-DUTY** [comment]
@Im-dex А по удобности для программиста?)

**Comment by Im-dex** [comment]
@ForserX Миллисекунды мне не особо интересны

@Xottab-DUTY Конечно pugi удобнее: не надо с указателями возиться, есть опции парсинга, хорошая дока + есть ~~SAX~~ XPATH из коробки

**Comment by Xottab-DUTY** [comment]
@Im-dex спасибо) Если руки дойдут, тогда перейду у себя на pugi. Ещё вопросик: ничего не скажешь по поводу rapidxml?

**Comment by Im-dex** [comment]
@Xottab-DUTY Не пользовался им, но вроде весьма популярный

**Comment by Xottab-DUTY** [comment]
@Im-dex надо будет и с ним сравнить)

**Comment by ForserX** [comment]
@Im-dex, популярный или нет, но я от лени в свой двиг затащил Тини от xr, т.к. было лень качать и изучать что-то другое. Не судите строго :)
