### ISSUE TITLE
On game crash: game gets stuck in loop

### ISSUE THREAD

**Issue by ghost** [Im-dex/xray-162#39]
On the rare occasion where the mod crashes for whatever reason (usually something I did wrong), the error box pops up, I click cancel or end task, whatever, but then it pops right back up, over and over, and doesn't go away. Because of this I often end up playing the game in a window, as otherwise I can't ctrl+alt+del to get to task manager and kill the process.

**Comment by Im-dex** [comment]
Thanks for the report. This is known bug and it should be fixed in the nearest updates.
