### ISSUE TITLE
CMake / Setup error?

### ISSUE THREAD

**Issue by derBABO88** [Im-dex/xray-162#65]
Hi,
I'm getting an error when trying to create the visual studio project file saying "Only MSVC 15.5 (MSVS 2017) and higher is supported" eventhough I am using Visual Studio 2017 (Version 15.7.3). Clearly this version should be supported.

Any ideas what could be causing this?

**Comment by ForserX** [comment]
Code not ported to 15.7. Use X-Ray Oxygen

**Comment by Xottab-DUTY** [comment]
>Clearly this version should be supported.

Unfortunately, but it is not.

The project is freezed. You can try to support it and send of PR with fix or switch to other project. There's a plenty of repositories related to X-Ray 1.6, just search it on a github. =)

**Comment by Im-dex** [comment]
@derBABO88 
It is just an incorrect version check within root CMakeLists. You could fix or remove it to fix solution generation

**Comment by ForserX** [comment]
@Im-dex, там всё равно не соберётся. Код придётся переносить.

**Comment by Xottab-DUTY** [comment]
Ну, а вдруг соберётся? Мне, вот, вообще не пришлось переносить)
